import Head from 'next/head';
import EnableScale from '../components/AboutUs/EnableScale';
import Hero from '../components/AboutUs/Hero';
import DojahLand from '../components/Careers/DojahLand';
import Video from '../components/Video';

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - About Us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <section className="bg-secondary py-20 -mt-[41px] z-50 relative">
        <div className="mx-auto max-w-[1195px]">
          <Video />
        </div>
      </section>
      <EnableScale />
      <DojahLand
        heading="Become a citizen of the Dojah-land"
        paragraph="We’re not just a team, we’re a diverse group of people with the same values and purpose. Join like minds who want to do impactful work, grow their careers and support their colleagues."
        linkText="See open roles"
      />
    </div>
  );
}
