import Head from 'next/head';
import Hero from '../components/BrandKit/Hero';
import Kits from '../components/BrandKit/Kits';

export default function BrandKit() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Brand Kit</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <Kits />
    </div>
  );
}
