import Head from 'next/head';
import DojahLand from '../components/Careers/DojahLand';
import Hero from '../components/Careers/Hero';
import Positions from '../components/Careers/Positions';
import WhyJoin from '../components/Careers/WhyJoin';
import Layout from '../components/Layout';

export default function Careers() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Careers</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <Positions />
      <WhyJoin />
      <DojahLand
        heading="Life in Dojah-land"
        paragraph="We’re not just a team, we’re a diverse group of people with the same values and purpose. Join like minds who want to do impactful work, grow their careers and support their colleagues."
        linkText="Read our team stories here"
      />
    </Layout>
  );
}
