import Head from 'next/head';
import Hero from '../components/ContactSales/Hero';
import Demo from '../components/ContactSales/Demo';
import Enquiries from '../components/ContactSales/Enquiries';
import GeneralEnquiries from '../components/ContactSales/GeneralEnquiries';

export default function ContactSales() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Contact sales</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <Demo />
      <Enquiries />
      <GeneralEnquiries />
    </div>
  );
}
