import Head from 'next/head';
import PowerfulAutomation from '../components/AllProducts/PowerfulAutomation';
import CustomerStories from '../components/CustomerStories';
import PurposeBuilt from '../components/FinancialServices/PurposeBuilt';
import TopNotchSecurity from '../components/FraudDetection/TopNotchSecurity';
import HeroLight from '../components/HeroLight';
import VerificationTime from '../components/VerificationTime';

export default function FinancialServices() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Financial Services</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroLight
        heading="Balance compliance and conversion rate for BNPL Platforms"
        paragraph="Use Financial data, Biometric data, Government data, Telco data and AML data to onboard verified customers at all stages of your product with Dojah"
      />
      <TopNotchSecurity
        text1="Single platform for all verification processes and reports"
        text2="Reduce operational costs with automated verification"
        text3="Easily detect frauds and risks with instant and reliable data"
        text4="Optimize conversion rates with frictionless verification"
      />
      <VerificationTime />
      <PurposeBuilt />
      <div className="bg-[#ECF3FF] py-28">
        <CustomerStories />
      </div>
      <PowerfulAutomation />
    </div>
  );
}
