import Head from 'next/head';
import {fraudPreventionHero} from '../assets/images/images';
import CustomerStories from '../components/CustomerStories';
import CustomFlows from '../components/FraudDetection/CustomFlows';
import SuspiciousSignups from '../components/FraudDetection/SuspiciousSignups';
import TopNotchSecurity from '../components/FraudDetection/TopNotchSecurity';
import HeroLight from '../components/HeroLight';
import Layout from '../components/Layout';

export default function FraudDetection() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Fraud Detection</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroLight
        heading="Onboarding tools to balance fraud prevention with customer experience"
        paragraph="Spot fake ID documents, implement AML sanctions, detect fraud patterns and approve trusted users fast."
        illustration={fraudPreventionHero}
      />
      <TopNotchSecurity
        text1="Enable top-notch security of users on your platform"
        text2="Automate identity and access management"
        text3="Enhance your decision-making process"
        text4="Retain genuine customers and grow revenue"
      />
      <SuspiciousSignups />
      <CustomFlows />
      <div className="bg-[#ECF3FF] py-28">
        <CustomerStories />
      </div>
    </Layout>
  );
}
