import Head from 'next/head';
import {geolocationHero} from '../assets/images/images';
import AddressData from '../components/AllProducts/AddressData';
import BusinessSafe from '../components/AllProducts/AddressVerification/BusinessSafe';
import ComprehensiveData from '../components/AllProducts/AddressVerification/ComprehensiveData';
import EfficientOperations from '../components/AllProducts/AddressVerification/EfficientOperations';
import SoftJob from '../components/AllProducts/SoftJob';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import Pricing from '../components/Pricing';

export default function Geolocation() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Geolocation</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Simplify fraud prevention with a comprehensive device and address data"
        paragraph="Digitally capture and verify customer’s address within seconds in xyz+ countries and locations."
        illustration={geolocationHero}
      />
      <AddressData
        text1="Detect malicious attempts before it becomes fraud."
        text2="Eliminate the time spent manually correcting address errors."
        text3="AI-powered verification results in a 99% accuracy rate for the prevention of identity fraud"
      />
      <BusinessSafe heading="Keep your business safe and operational costs down" />
      <EfficientOperations />
      <ComprehensiveData />
      <SoftJob />
      <Pricing />
    </Layout>
  );
}
