import Head from 'next/head';
import CustomerStories from '../components/LandingPage/CustomerStories';
import CustomWorkflow from '../components/LandingPage/CustomWorkflow';
import DirectIntegration from '../components/LandingPage/DirectIntegration';
import Hero from '../components/LandingPage/Hero';
import MakeItScale from '../components/LandingPage/MakeItScale';
import NoCodeTools from '../components/LandingPage/NoCodeTools';
import Partners from '../components/Partners';
import Pricing from '../components/Pricing';
import Tools from '../components/LandingPage/Tools';
import Widgets from '../components/LandingPage/Widgets';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <DirectIntegration />
      <Widgets />
      <NoCodeTools />
      <CustomWorkflow />
      <MakeItScale />
      <Partners />
      <Tools />
      <CustomerStories />
      <Pricing />
    </div>
  );
}
