import Head from 'next/head';
import PowerfulAutomation from '../components/AllProducts/PowerfulAutomation';
import HeroLight from '../components/HeroLight';
import ProtectBrand from '../components/ProtectBrand';
import Verification from '../components/Verification';
import VerificationTime from '../components/VerificationTime';

export default function Logistics() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Logistics</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroLight
        heading="The full package onboarding kit to verify drivers"
        paragraph="Ensure top-notch service delivery with real-time capture and verification of Address data, Biometric data, Government Data, IP/Device checks and more."
      />
      <ProtectBrand
        text1="Protect your brand by ensuring only legit drivers are onboarded"
        text2="Reduce operational costs with automated verifications"
        text3="Detect frauds and reduce risks with reliable and instant data"
      />
      <VerificationTime />
      <section className="bg-white-800 py-24">
        <div className="max-w-[1051px] mx-auto mb-20">
          <h3 className="text-center mx-auto text-secondary text-2lg font-bold max-w-3xl">
            Onboard trusted drivers and make service delivery smooth for
            recipients
          </h3>
        </div>
        <Verification
          paragraph2="
        Automatically check and verify driver's license and other KYC documents."
          heading3="Document Verification"
          paragraph3="Spot forgery, extract and verify data from vehicle documents accurately"
          explore
        />
      </section>
      <PowerfulAutomation />
    </div>
  );
}
