import Head from 'next/head';
import {retailHero} from '../assets/images/images';
import CustomerStories from '../components/CustomerStories';
import CustomFlows from '../components/FraudDetection/CustomFlows';
import SuspiciousSignups from '../components/FraudDetection/SuspiciousSignups';
import HeroLight from '../components/HeroLight';
import Layout from '../components/Layout';
import ProtectBrand from '../components/ProtectBrand';

export default function OnboardingVerification() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Onboarding and verification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroLight
        heading="Make it easy for verified users to access all the services on your platform"
        paragraph="Onboard more users without sacrificing fraud prevention, compliance and customer experience."
        illustration={retailHero}
      />
      <ProtectBrand
        text1="Enable top-notch security of users on your platform"
        text2="Automate identity and access management"
        text3="Enhance your decision-making process"
      />
      <SuspiciousSignups />
      <CustomFlows />
      <div className="bg-[#ECF3FF] py-28">
        <CustomerStories />
      </div>
    </Layout>
  );
}
