import Head from 'next/head';
import Hero from '../components/PrivacyPolicy/Hero';
import Policy from '../components/PrivacyPolicy/Policy';

export default function PrivacyPolicy() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <Policy />
    </div>
  );
}
