import Head from 'next/head';
import PowerfulAutomation from '../components/AllProducts/PowerfulAutomation';
import HeroLight from '../components/HeroLight';
import ProtectBrand from '../components/ProtectBrand';
import Verification from '../components/Verification';
import VerificationTime from '../components/VerificationTime';

export default function RetailEcommerce() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Logistics</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroLight
        heading="Increase checkout rates and build trust in your platform"
        paragraph="Ensure top-notch service delivery with real-time capture and verification of Address data, Biometric data, Government Data, IP/Device checks and more."
      />
      <ProtectBrand
        text1="Remove onboarding and checkout friction for shoppers"
        text2="Reduce operational costs with automated verification"
        text3="Detect frauds and reduce risks with reliable and instant data"
      />
      <VerificationTime />
      <section className="bg-white-800 py-24">
        <div className="max-w-[1051px] mx-auto mb-20">
          <h3 className="text-center mx-auto text-secondary text-2lg font-bold max-w-3xl">
            Get rid of scammers, don’t delay ready-to-pay customers
          </h3>
        </div>
        <Verification
          paragraph2="
        Automatically check and verify driver's license and other KYC documents."
          heading3="Document Verification"
          paragraph3="Spot forgery, extract and verify data from vehicle documents accurately"
          explore
        />
        <div className="mt-20" />
        <Verification
          heading1="Address Verification"
          paragraph1="Automatically capture and validate the physical location of your recipients."
          heading2="IP & Device Check"
          paragraph2="Check IP addresses and identify devices from anywhere in the world."
          heading3="Financial Connections"
          paragraph3="Get bank data such as account statements, balance, identity, and more with your users’ permission."
          explore
        />
      </section>
      <PowerfulAutomation />
    </div>
  );
}
