import Head from 'next/head';
import Layout from '../components/Layout';
import Hero from '../components/TermsOfService/Hero';
import Terms from '../components/TermsOfService/Terms';

export default function TermsOfService() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Terms of service</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <Terms />
    </Layout>
  );
}
