import Head from 'next/head';
import {useCallback, useEffect, useState} from 'react';
import {
  amlCheckProduct,
  emailCheckProduct,
  ipDeviceCheckProduct,
  livenessCheckProduct,
  phoneNumberCheckProduct,
} from '../../assets/images/images';
import ProductsLayout from '../../components/AllProducts/ProductsLayout';
import Layout from '../../components/Layout';

const AUTHENTICATION_AND_CHECKS = [
  {
    src: ipDeviceCheckProduct,
    largeText: 'IP and Device Check',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/ip-device-check',
  },
  {
    src: emailCheckProduct,
    largeText: 'Email Check',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/email-check',
  },
  {
    src: phoneNumberCheckProduct,
    largeText: 'Phone Number Check',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/phone-number-check',
  },
  {
    src: livenessCheckProduct,
    largeText: 'Liveness Check',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/liveness-check',
  },
  {
    src: amlCheckProduct,
    largeText: 'Anti-Money Laundering Check',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/government-id-verification',
  },
];

export default function AuthenticationAndChecks() {
  const [selectedProducts, setSelectedProducts] = useState('');

  const [filteredProducts, setFilteredProducts] = useState(
    AUTHENTICATION_AND_CHECKS,
  );

  const filterByProducts = useCallback(
    filteredData => {
      if (selectedProducts === '') {
        return filteredData;
      }

      const filteredItems = filteredData.filter(
        r =>
          r.largeText.toLowerCase().indexOf(selectedProducts.toLowerCase()) !==
          -1,
      );

      return filteredItems;
    },
    [selectedProducts],
  );

  useEffect(() => {
    const filteredData = filterByProducts(AUTHENTICATION_AND_CHECKS);
    setFilteredProducts(filteredData);
  }, [filterByProducts]);
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - All Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductsLayout
        ALL_PRODUCTS={filteredProducts}
        selectedProducts={selectedProducts}
        setSelectedProducts={setSelectedProducts}
      />
    </Layout>
  );
}
