import Head from 'next/head';
import Hero from '../../components/Hero';
import SoftJob from '../../components/AllProducts/SoftJob';
import Partners from '../../components/Partners';
import FinancialService from '../../components/AllProducts/FinancialService';
import {bankAccountIllustration} from '../../assets/images/images';
import Layout from '../../components/Layout';

export default function BankAccountVerification() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Bank Account Verification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero
        heading="Fetch and verify identity data from Bank Account Number"
        paragraph="Access all the data required for onboarding to your application with a NUBAN. Easier onboarding for your users."
        illustration={bankAccountIllustration}
      />
      <Partners />
      <FinancialService
        heading1="Make it easy for users to switch to your financial service with an existing NUBAN"
        heading2="Expansive coverage across all banks"
        paragraph="Our Nigeria Uniform Bank Account Number endpoint provides information on users' account numbers across all Nigerian banks."
      />
      <SoftJob />
    </Layout>
  );
}
