import Head from 'next/head';
import Hero from '../../components/Hero';
import CardsPartners from '../../components/AllProducts/CardsPartners';
import {biometricVerificationHero, stopwatch} from '../../assets/images/images';
import Layout from '../../components/Layout';
import SoftJob from '../../components/AllProducts/SoftJob';
import VerificationService from '../../components/VerificationService';
import BusinessSafe from '../../components/AllProducts/AddressVerification/BusinessSafe';
import FraudProof from '../../components/FraudProof';

export default function BiometricVerification() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Biometric Verification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero
        heading={
          <>
            Confirm user identity with {''}
            <span>facial biometrics</span>
          </>
        }
        paragraph="Verify users with a short video or selfie. Dojah checks that the user is live and their facial biometrics matches a valid ID."
        illustration={biometricVerificationHero}
      />
      <CardsPartners
        image1={stopwatch}
        image2={stopwatch}
        image3={stopwatch}
        text1="Onboard users with a biometric verification"
        text2="An added layer of protection for your users"
        text3="Make verification seamless with biometrics"
      />
      <VerificationService />
      <BusinessSafe
        largeText1="Production-ready integration"
        paragraph1="Dojah provides flexible integration options and libraries that help you deploy identity verification at scale without compromising on your onboarding experience."
        largeText2="Enrol once, get robust data"
        paragraph2="One-time integration allows you to verify all types of KYC documents across African countries in seconds through Dojah’s robust identity lookup service."
      />
      <FraudProof />
      <SoftJob />
    </Layout>
  );
}
