import Head from 'next/head';
import {
  easyLookupHero,
  simpleTools,
  singleIntegration,
} from '../../assets/images/images';
import AddressData from '../../components/AllProducts/AddressData';
import IdentifyCustomers from '../../components/AllProducts/EasyLookup/IdentifyCustomers';
import PowerfulAutomation from '../../components/AllProducts/PowerfulAutomation';
import Hero from '../../components/Hero';
import Layout from '../../components/Layout';
import Uploads from '../../components/Uploads';

export default function EasyLookup() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Easy Lookup</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Lookup and verify Government data without coding"
        paragraph="Directly identify your customers across multiple IDs in real time. You can easily take charge of your users’ identities."
        illustration={easyLookupHero}
      />
      <AddressData
        text1="Navigate identity verification processes  with no-code"
        text2="Handle customer data without the cost of hiring developers"
        text3="Access to several databases across multiple countries in no-time"
      />
      <IdentifyCustomers />
      <Uploads
        src1={simpleTools}
        heading1="Individual/Bulk uploads"
        body1="Obtain the information of one customer or multiple customers in one process."
        body2="Explore a wide range of options to identify your customers as you deem fit."
        heading2="Multiple ID selection"
        src2={singleIntegration}
      />
      <PowerfulAutomation />
    </Layout>
  );
}
