import Head from 'next/head';
import {
  easyOnboardHero,
  simpleTools,
  singleIntegration,
} from '../../assets/images/images';
import AddressData from '../../components/AllProducts/AddressData';
import SmoothOnboarding from '../../components/AllProducts/EasyOnboard/SmoothOnboarding';
import PowerfulAutomation from '../../components/AllProducts/PowerfulAutomation';
import Hero from '../../components/Hero';
import Layout from '../../components/Layout';
import Uploads from '../../components/Uploads';

export default function EasyOnboard() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Easy Onboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Onboard and verify users easily with robust no-code tools"
        paragraph="With Dojah, it's easier to onboard users, reduce fraud, and adopt compliance checks across several countries—no developer experience needed."
        illustration={easyOnboardHero}
      />
      <AddressData
        text1="Balance user experience and strong identity verification"
        text2="Handle customer data without the cost of hiring developers"
        text3="Custom onboarding flows that match your branding"
      />
      <SmoothOnboarding
        heading="Create a smooth onboarding flow on your own terms"
        text1="Setup your app and fully customise your users’ experience on the Dojah dashboard."
        text2="Create a custom onboarding flow or select from our library of pre-existing templates"
        text3="Configure your onboarding widget with options for manual or automatic verification, preferred verification type and many more functionalities."
        text4="Configure your onboarding widget with options for manual or automatic verification, preferred verification type and many more functionalities."
      />
      <Uploads
        src1={simpleTools}
        heading1="Ready-made  flows"
        body1="Explore pre-defined verification templates to fit different use cases and stages of user onboarding. Get a headstart on bringing trusted users to your platform."
        heading2="Built for teamwork"
        body2="Invite other members of your team to manage your configurations, verify data, leave feedback, get approvals, and handle customer support."
        src2={singleIntegration}
      />
      <PowerfulAutomation docData />
    </Layout>
  );
}
