import Head from 'next/head';
import {
  easyConnectHero,
  simpleTools,
  singleIntegration,
} from '../../assets/images/images';
import AddressData from '../../components/AllProducts/AddressData';
import FinancialData from '../../components/AllProducts/EasyConnect/FinancialData';
import PowerfulAutomation from '../../components/AllProducts/PowerfulAutomation';
import Hero from '../../components/Hero';
import Layout from '../../components/Layout';
import Uploads from '../../components/Uploads';

export default function EasyConnect() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Easy Connect</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Connect to your users’ financial data with no code"
        paragraph="Access financial information, build financial products, improve product experience—no coding required."
        illustration={easyConnectHero}
      />
      <AddressData
        text1="Build and deploy financial products and processes faster"
        text2="Handle customer data without the cost of hiring developers"
        text3="Reduce drop-off during checkout and other processes"
      />
      <FinancialData />
      <Uploads
        src1={simpleTools}
        heading1="Individual/Bulk uploads"
        body1="Obtain the information of one customer or multiple customers in one process."
        body2="Explore a wide range of options to identify your customers as you deem fit."
        heading2="Multiple ID selection"
        src2={singleIntegration}
      />
      <PowerfulAutomation />
    </Layout>
  );
}
