import Head from 'next/head';
import Hero from '../../components/Hero';
import CardsPartners from '../../components/AllProducts/CardsPartners';
import {emailCheckIllustration, stopwatch} from '../../assets/images/images';
import NextLevelProof from '../../components/AllProducts/NextLevelProof';
import Pricing from '../../components/Pricing';
import Layout from '../../components/Layout';

export default function EmailCheck() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Email Check</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        illustration={emailCheckIllustration}
        heading="Verify identity with an email address. Onboard high-quality users."
        paragraph="Filter invalid email addresses and recognize fraud patterns early with instant identity verification via mail."
      />
      <CardsPartners
        image1={stopwatch}
        image2={stopwatch}
        image3={stopwatch}
        text1="Accurate results obtained in real-time"
        text2="Reach more customers and increase profits"
        text3="Increase in transparency and verification speed."
      />
      <NextLevelProof />
      <Pricing />
    </Layout>
  );
}
