import {useCallback, useEffect, useState} from 'react';
import Head from 'next/head';
import {
  accessBankAccountsVerificationProduct,
  finTransactionAnalysisProduct,
  linkBankAccountsVerificationProduct,
} from '../../assets/images/images';
import ProductsLayout from '../../components/AllProducts/ProductsLayout';

const FINANCIAL_SERVICES = [
  {
    src: linkBankAccountsVerificationProduct,
    largeText: 'Link Bank Accounts',
    smallText: 'Retrieve account transaction details',
    link: '/all-products/government-id-verification',
  },
  {
    src: accessBankAccountsVerificationProduct,
    largeText: 'Access Bank Accounts',
    smallText: 'Retrieve account transaction details',
    link: '/all-products/government-id-verification',
  },
  {
    src: finTransactionAnalysisProduct,
    largeText: 'Fin. Transaction Analysis',
    smallText: 'Analyse spending patterns and transactions',
    link: '/all-products/government-id-verification',
  },
];

export default function FinancialServices() {
  const [selectedProducts, setSelectedProducts] = useState('');

  const [filteredProducts, setFilteredProducts] = useState(FINANCIAL_SERVICES);

  const filterByProducts = useCallback(
    filteredData => {
      if (selectedProducts === '') {
        return filteredData;
      }

      const filteredItems = filteredData.filter(
        r =>
          r.largeText.toLowerCase().indexOf(selectedProducts.toLowerCase()) !==
          -1,
      );

      return filteredItems;
    },
    [selectedProducts],
  );

  useEffect(() => {
    const filteredData = filterByProducts(FINANCIAL_SERVICES);
    setFilteredProducts(filteredData);
  }, [filterByProducts]);

  return (
    <div>
      <Head>
        <title>Dojah web v3 - All Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductsLayout
        ALL_PRODUCTS={filteredProducts}
        selectedProducts={selectedProducts}
        setSelectedProducts={setSelectedProducts}
      />
    </div>
  );
}
