import Head from 'next/head';
import Hero from '../../components/Hero';
import Pricing from '../../components/Pricing';
import CardsPartners from '../../components/AllProducts/CardsPartners';
import {
  ai,
  clock,
  documentVerificationIllustration,
  stopwatch,
} from '../../assets/images/images';
import VerifyDocument from '../../components/AllProducts/DocumentVerification/VerifyDocument';
import SupportedIds from '../../components/AllProducts/DocumentVerification/SupportedIds';
import Layout from '../../components/Layout';
import SoftJob from '../../components/AllProducts/SoftJob';

export default function FinancialConnection() {
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - Financial Connection</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero
        heading="Access financial data. Verify financial reputation. Build better products."
        paragraph="Capture, extract and screen information on several ID document types within Africa in seconds"
        illustration={documentVerificationIllustration}
      />
      <CardsPartners
        image1={stopwatch}
        image2={clock}
        image3={ai}
        text1="Optimize conversion rates. Verify users within 30-60 seconds."
        text2="Save time and operational costs. Automate data extraction."
        text3="AI-powered verification results for prevention of identity fraud"
      />
      <VerifyDocument />
      <SupportedIds />
      <SoftJob />
      <Pricing />
    </Layout>
  );
}
