import {useCallback, useEffect, useState} from 'react';
import Head from 'next/head';
import ProductsLayout from '../../components/AllProducts/ProductsLayout';
import {
  addressVerificationProduct,
  bankAccountVerificationProduct,
  biometricVerificationProduct,
  documentVerificationProduct,
  governmentVerificationProduct,
} from '../../assets/images/images';
import Layout from '../../components/Layout';

const IDENTITY_VERIFICATION = [
  {
    src: governmentVerificationProduct,
    largeText: 'Government ID Verification',
    smallText: 'KYC check and verification',
    link: '/all-products/government-id-verification',
  },
  {
    src: documentVerificationProduct,
    largeText: 'Document Verification',
    smallText: 'Extract and verify document data',
    link: '/all-products/document-verification',
  },
  {
    src: biometricVerificationProduct,
    largeText: 'Biometric Verification',
    smallText: 'Authenticate users with facial biometrics',
    link: '/all-products/government-id-verification',
  },
  {
    src: addressVerificationProduct,
    largeText: 'Address Verification',
    smallText: 'Capture and validate physical location',
    link: '/all-products/address-verification',
  },
  {
    src: bankAccountVerificationProduct,
    largeText: 'Financial Connection',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/financial-connection',
  },
];

export default function IdentityVerification() {
  const [selectedProducts, setSelectedProducts] = useState('');

  const [filteredProducts, setFilteredProducts] = useState(
    IDENTITY_VERIFICATION,
  );

  const filterByProducts = useCallback(
    filteredData => {
      if (selectedProducts === '') {
        return filteredData;
      }

      const filteredItems = filteredData.filter(
        r =>
          r.largeText.toLowerCase().indexOf(selectedProducts.toLowerCase()) !==
          -1,
      );

      return filteredItems;
    },
    [selectedProducts],
  );

  useEffect(() => {
    const filteredData = filterByProducts(IDENTITY_VERIFICATION);
    setFilteredProducts(filteredData);
  }, [filterByProducts]);
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - All Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductsLayout
        ALL_PRODUCTS={filteredProducts}
        selectedProducts={selectedProducts}
        setSelectedProducts={setSelectedProducts}
      />
    </Layout>
  );
}
