import Head from 'next/head';
import Hero from '../../components/Hero';
import Pricing from '../../components/Pricing';
import CardsPartners from '../../components/AllProducts/CardsPartners';
import {
  ipDeviceCheckIllustration,
  maliciousAttempts,
  protect,
  transparency,
} from '../../assets/images/images';
import NextLevelProof from '../../components/AllProducts/NextLevelProof';
import IdentifyLocation from '../../components/AllProducts/IpDeviceCheck/IdentifyLocation';

export default function IpDeviceCheck() {
  return (
    <div>
      <Head>
        <title>Dojah web v3 - Document Verification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero
        illustration={ipDeviceCheckIllustration}
        heading="Verify devices and their exact location when onboarding"
        paragraph="Detect VPN/Proxy access, accurately locate your users around the world, and also geo-restrict based on geographical areas"
      />
      <CardsPartners
        image1={transparency}
        image2={maliciousAttempts}
        image3={protect}
        text1="Increase in transparency and verification speed."
        text2="Detect malicious attempts before it becomes fraud."
        text3="Help your users protect their account activities."
      />
      <IdentifyLocation />
      <NextLevelProof />
      <Pricing />
    </div>
  );
}
