import Head from 'next/head';
import {useCallback, useEffect, useState} from 'react';
import {
  easyConnectProduct,
  easyLookupProduct,
  easyOnboardProduct,
} from '../../assets/images/images';
import ProductsLayout from '../../components/AllProducts/ProductsLayout';

const NO_CODE_TOOLS = [
  {
    src: easyLookupProduct,
    largeText: 'Easy Lookup',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/easy-lookup',
  },
  {
    src: easyConnectProduct,
    largeText: 'Easy Connect',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/easy-connect',
  },
  {
    src: easyOnboardProduct,
    largeText: 'Easy Onboard',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/easy-onboard',
  },
];

export default function NoCodeTools() {
  const [selectedProducts, setSelectedProducts] = useState('');

  const [filteredProducts, setFilteredProducts] = useState(NO_CODE_TOOLS);

  const filterByProducts = useCallback(
    filteredData => {
      if (selectedProducts === '') {
        return filteredData;
      }

      const filteredItems = filteredData.filter(
        r =>
          r.largeText.toLowerCase().indexOf(selectedProducts.toLowerCase()) !==
          -1,
      );

      return filteredItems;
    },
    [selectedProducts],
  );

  useEffect(() => {
    const filteredData = filterByProducts(NO_CODE_TOOLS);
    setFilteredProducts(filteredData);
  }, [filterByProducts]);
  return (
    <div>
      <Head>
        <title>Dojah web v3 - All Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductsLayout
        ALL_PRODUCTS={filteredProducts}
        selectedProducts={selectedProducts}
        setSelectedProducts={setSelectedProducts}
      />
    </div>
  );
}
