import Head from 'next/head';
import {useCallback, useEffect, useState} from 'react';
import {
  financialDataWidgetProduct,
  idVerificationProduct,
} from '../../assets/images/images';
import ProductsLayout from '../../components/AllProducts/ProductsLayout';
import Layout from '../../components/Layout';

const WIDGETS = [
  {
    src: financialDataWidgetProduct,
    largeText: 'Financial Data Widget',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/government-id-verification',
  },
  {
    src: idVerificationProduct,
    largeText: 'ID Verification Widget',
    smallText: 'Look up and verify users with NUBAN',
    link: '/all-products/government-id-verification',
  },
];

export default function Widgets() {
  const [selectedProducts, setSelectedProducts] = useState('');

  const [filteredProducts, setFilteredProducts] = useState(WIDGETS);

  const filterByProducts = useCallback(
    filteredData => {
      if (selectedProducts === '') {
        return filteredData;
      }

      const filteredItems = filteredData.filter(
        r =>
          r.largeText.toLowerCase().indexOf(selectedProducts.toLowerCase()) !==
          -1,
      );

      return filteredItems;
    },
    [selectedProducts],
  );

  useEffect(() => {
    const filteredData = filterByProducts(WIDGETS);
    setFilteredProducts(filteredData);
  }, [filterByProducts]);
  return (
    <Layout>
      <Head>
        <title>Dojah web v3 - All Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductsLayout
        ALL_PRODUCTS={filteredProducts}
        selectedProducts={selectedProducts}
        setSelectedProducts={setSelectedProducts}
      />
    </Layout>
  );
}
